### PR TITLE
Option

### PR DESCRIPTION
**Pull request by KJ12124**
reid option 추가 했습니다.

### CODE REVIEW

**Comment by mikel-brostrom** [comment]
Hi!

Thank you for the PR! I could not get this running after installing the requirements.txt

Moreover, I would help if you could provide an overall explanation of what has been added and deleted.

**Comment by KJ12124** [comment]
I'm sorry. I'm a student in Korea and I think I sent the wrong PR while doing the personal project with the technology. Sorry.

**Comment by mikel-brostrom** [comment]
I just skimmed through your code and see that you used TorchREID. It would be fantastic to have the possibility to switch between different REID methods. If you find time to PR this I would be more than glad to review that code.

**Comment by cross-hello** [comment]
I can't found *torchreid* pip package. Anyone would give a hand? 
>ERROR: Could not find a version that satisfies the requirement torchreid (from versions: none)
ERROR: No matching distribution found for torchreid

**Comment by mikel-brostrom** [comment]
TorchReID is used as a submodule in this repo. Check:

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/tree/master/deep_sort/deep

**Comment by cross-hello** [comment]
@mikel-brostrom  Thank you, I got it in [here](https://kaiyangzhou.github.io/deep-person-reid#installation)

**Pull request closed without merging**
