### PR TITLE
using Submodules - Yolo5 + Deep_sort

### PR DESCRIPTION
**Pull request by Borda**
This is basically removing hard copy of both repositories and adding them as sub-modules some when ever any update is made in the particular dependency is projected also here

Pitch: The Yolo5 is till in development so it would be easier to have this live connection so users can always get the latest version

### CODE REVIEW

**Comment by mikel-brostrom** [comment]
This is a much needed update for this repo. I will
try to find some time in the coming days to have a look at this.
Thanks!

**Comment by Borda** [comment]
@mikel-brostrom you can simply follow the steps as per commit:
1. remove hard copy
2. add the same repos as submodules
3. update paths accordingly and add note to readme that it shall be checkout recursively

**Comment by Borda** [comment]
@mikel-brostrom how is it going? :]

**Comment by Borda** [comment]
@mikel-brostrom ^^

**Comment by mikel-brostrom** [comment]
It took me some time to learn git submodules... Never used them before... :)

**Comment by mikel-brostrom** [comment]
However, I now get some import issues but had no problem when I pulled your version. I will have a look at this

**Comment by mikel-brostrom** [comment]
When I change 

sys.path.insert(0, os.path.abspath('./deep_sort'))

to 

sys.path.insert(0, os.path.abspath('./deep_sort_pytorch'))

the import error seem to disappear although the folder is called deep_sort, Any idea why this is?

**Comment by Borda** [comment]
not sure, maybe the mapping in `.submodules` does not work correctly and still uses the original/target folder which is `deep_sort_pytorch`

**Comment by mikel-brostrom** [comment]
Weird...

**Pull request merged**
