### PR TITLE
Multi tracking is now possible!!!

### PR DESCRIPTION
**Pull request by hdnh2006**
With this PR yolov5 deepsort will be able to track multiple cameras!!!

Just run the code `track.py` as yolov5 does:
`python track.py --source streams.txt`
where `streams.txt` is
```
rtsp://yoururl.com
rtmp://yoururl2.com
```

Let me know any suggestion.

### CODE REVIEW

**Comment by mikel-brostrom** [comment]
This would be a nice addition to this repo. It would be sweet if we could keep it as simple as possible by just adding the sources as input arguments for `--source`

**Comment by hdnh2006** [comment]
Hi @mikel-brostrom, you can use the parameter `--source` as input of the code `track.py`. In the case of my PR, you can pass `--source streams.txt`, where `streams.txt` is just a file like the original yolov5 repo does:
```
rtsp://yoururl1.com
rtsp://yoururl2.com
0 (for webcam)
```

I already did some suggestion a few months ago (https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/issues/88#issuecomment-839671616) but I thought somebody could do the PR for me. I don't have too much time. 

I also did a new commit which is able to save each streams, please check my git: https://github.com/hdnh2006/Yolov5_DeepSort_Pytorch

So please Mikel, if you need some help, let me know.

**Comment by mikel-brostrom** [comment]
> I also did a new commit which is able to save each streams, please check my git: https://github.com/hdnh2006/Yolov5_DeepSort_Pytorch

I see. I will add the latest updates to the branch. Thank you for your contribution!

**Comment by hdnh2006** [comment]
I am happy to appear here as a contributor:
image

I actually suggested in the past this modification in a comment: https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/issues/88#issuecomment-839671616

Unfortunately my time is limited and I had not been able to do this PR, but this repo has helped me a lot and I wanted to contribute with it.

Congratulations!

**Pull request merged**
